format = """
[](#9A348E)\
$os\
$username\
[ ](#9A348E)\
[](#DA627D)\
$directory\
[](#DA627D)\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
[ ](#33658A)\
$time\
[](#33658A)\
\n[󱞪 ](fg:yellow)\
"""

add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
format = "[$symbol ]($style)"
disabled = false

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"
truncate_to_repo = true
read_only ="  "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ ](#06969A)[ $symbol $context ]($style) $path[](#06969A)'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ ](#FCA17D)[ $symbol $branch ]($style)[](#FCA17D)'

[git_status]
style = "bg:#FFDC72"
format = '([ ](#FFDC72)[ $all_status$ahead_behind ]($style)[](#FFDC72))'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[gradle]
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ ](#86BBD8)[ $symbol ($version) ]($style)[](#86BBD8)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[  $time ]($style)'

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
